version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ts-loader
    versions:
    - 8.0.14
    - 8.0.15
    - 8.0.16
    - 8.0.17
    - 8.0.18
    - 8.1.0
    - 8.2.0
    - 9.0.2
    - 9.1.0
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: buefy
    versions:
    - 0.9.4
    - 0.9.5
    - 0.9.6
  - dependency-name: "@types/marked"
    versions:
    - 1.2.1
    - 1.2.2
    - 2.0.0
    - 2.0.1
  - dependency-name: y18n
    versions:
    - 4.0.1
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cairosvg
    versions:
    - 2.5.0
