environment:
  nodejs_version: "LTS"
  matrix:
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
build: off
install:
  - install-cairo.ps1
  - "%PYTHON%\\python.exe -m pip install pycodestyle"
  - "%PYTHON%\\python.exe -m pip install cryptography lxml"
  - "%PYTHON%\\python.exe setup.py install"
  - ps: Install-Product node $env:nodejs_version
  - npm install
before_test:
  - "%PYTHON%\\Scripts\\pycodestyle.exe ."
  - npm run lint
  - npm run debug
test_script:
  - "%PYTHON%\\python.exe setup.py test"
