environment:
  nodejs_version: "LTS"
  matrix:
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
build: off
install:
  - ps: |
      $cairoVersion = "1.15.10"
      $url = ([string]::Format("https://github.com/preshing/cairo-windows/releases/download/{0}/cairo-windows-{0}.zip", $cairoVersion))
      $output = "cairo.zip"
      $cairoPath = Join-Path $PSScriptROOT ([string]::Format("cairo-windows-{0}/lib/x64", $cairoVersion))

      [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
      Invoke-WebRequest -Uri $url -OutFile $output
      Expand-Archive $output -DestinationPath .
      $env:Path += ";" + $cairoPath
  - "%PYTHON%\\python.exe -m pip install pycodestyle"
  - "%PYTHON%\\python.exe -m pip install cryptography lxml"
  - "%PYTHON%\\python.exe setup.py install"
  - ps: Install-Product node $env:nodejs_version
  - npm install
before_test:
  - "%PYTHON%\\Scripts\\pycodestyle.exe ."
  - npm run lint
  - npm run debug
test_script:
  - "%PYTHON%\\python.exe setup.py test"
