image: Visual Studio 2017
environment:
  nodejs_version: "LTS"
  matrix:
    - PYTHON: "C:\\Python35"
      PYTHON_ARCH: 32
    - PYTHON: "C:\\Python36"
      PYTHON_ARCH: 32
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
build: off
install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python --version
  - ps: .\install-cairo.ps1
  - "%PYTHON%\\python.exe -m pip install pycodestyle"
  - "%PYTHON%\\python.exe -m pip install cryptography lxml tinycss2"
  - "%PYTHON%\\python.exe setup.py install"
  - ps: Install-Product node $env:nodejs_version
  - yarn
before_test:
  - "%PYTHON%\\Scripts\\pycodestyle.exe ."
  - yarn lint
  - yarn build
test_script:
  - "%PYTHON%\\python.exe setup.py test"
