environment:
  matrix:
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
build: off
install:
  - "%PYTHON%\\python.exe -m pip install pycodestyle"
  - "%PYTHON%\\python.exe setup.py install"
before_test:
  - "%PYTHON%\\Scripts\\pycodestyle.exe ."
test_script:
  - "%PYTHON%\\python.exe manage.py test"