image: Visual Studio 2017
environment:
  nodejs_version: "LTS"
  matrix:
    - PYTHON: "C:\\Python34"
      PYTHON_ARCH: 32
    - PYTHON: "C:\\Python35"
      PYTHON_ARCH: 32
    - PYTHON: "C:\\Python36"
      PYTHON_ARCH: 32
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
build: off
install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - ps: .\install-cairo.ps1
  - python -m pip install pycodestyle
  - python -m pip install cryptography lxml
  - python setup.py install
  - ps: Install-Product node $env:nodejs_version
  - yarn
before_test:
  - pycodestyle.exe .
  - yarn lint
  - yarn build
test_script:
  - python setup.py test
