language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
install:
  - sudo apt-get install libcairo2-dev
  - pip install pycodestyle codecov
  - python setup.py install
  - npm install
script:
  - make lint
  - npm run build
  - make coverage
after_success:
  - codecov
