language: python
python:
  - 3.4
  - 3.5
  - 3.6
install:
  - sudo apt-get install libcairo2-dev
  - pip install pycodestyle codecov
  - python setup.py install
  - yarn
script:
  - make lint
  - yarn build
  - make coverage
after_success:
  - codecov
