language: python
python:
  - 3.4
  - 3.5
  - 3.6
install:
  - apt-get install libcairo2-dev
  - pip install pycodestyle codecov
  - python setup.py install
  - npm install
script:
  - make lint
  - npm run debug
  - make coverage
after_success:
  - codecov
