export default {
    'agate': 'Agate',
    'androidstudio': 'Androidstudio',
    'arduino-light': 'Arduino Light',
    'arta': 'Arta',
    'ascetic': 'Ascetic',
    'atelier-cave-dark': 'Atelier Cave Dark',
    'atelier-cave-light': 'Atelier Cave Light',
    'atelier-dune-dark': 'Atelier Dune Dark',
    'atelier-dune-light': 'Atelier Dune Light',
    'atelier-estuary-dark': 'Atelier Estuary Dark',
    'atelier-estuary-light': 'Atelier Estuary Light',
    'atelier-forest-dark': 'Atelier Forest Dark',
    'atelier-forest-light': 'Atelier Forest Light',
    'atelier-heath-dark': 'Atelier Heath Dark',
    'atelier-heath-light': 'Atelier Heath Light',
    'atelier-lakeside-dark': 'Atelier Lakeside Dark',
    'atelier-lakeside-light': 'Atelier Lakeside Light',
    'atelier-plateau-dark': 'Atelier Plateau Dark',
    'atelier-plateau-light': 'Atelier Plateau Light',
    'atelier-savanna-dark': 'Atelier Savanna Dark',
    'atelier-savanna-light': 'Atelier Savanna Light',
    'atelier-seaside-dark': 'Atelier Seaside Dark',
    'atelier-seaside-light': 'Atelier Seaside Light',
    'atelier-sulphurpool-dark': 'Atelier Sulphurpool Dark',
    'atelier-sulphurpool-light': 'Atelier Sulphurpool Light',
    'atom-one-dark': 'Atom One Dark',
    'atom-one-light': 'Atom One Light',
    'brown-paper': 'Brown Paper',
    'codepen-embed': 'Codepen Embed',
    'color-brewer': 'Color Brewer',
    'darcula': 'Darcula',
    'dark': 'Dark',
    'darkula': 'Darkula',
    'default': 'Default',
    'docco': 'Docco',
    'dracula': 'Dracula',
    'far': 'Far',
    'foundation': 'Foundation',
    'github': 'Github',
    'github-gist': 'Github Gist',
    'googlecode': 'Googlecode',
    'grayscale': 'Grayscale',
    'gruvbox-dark': 'Gruvbox Dark',
    'gruvbox-light': 'Gruvbox Light',
    'hopscotch': 'Hopscotch',
    'hybrid': 'Hybrid',
    'idea': 'Idea',
    'ir-black': 'Ir Black',
    'kimbie.dark': 'Kimbie Dark',
    'kimbie.light': 'Kimbie Light',
    'magula': 'Magula',
    'mono-blue': 'Mono Blue',
    'monokai': 'Monokai',
    'monokai-sublime': 'Monokai Sublime',
    'obsidian': 'Obsidian',
    'ocean': 'Ocean',
    'paraiso-dark': 'Paraiso Dark',
    'paraiso-light': 'Paraiso Light',
    'pojoaque': 'Pojoaque',
    'purebasic': 'Purebasic',
    'qtcreator_dark': 'Qtcreator Dark',
    'qtcreator_light': 'Qtcreator Light',
    'railscasts': 'Railscasts',
    'rainbow': 'Rainbow',
    'routeros': 'Routeros',
    'school-book': 'School Book',
    'solarized-dark': 'Solarized Dark',
    'solarized-light': 'Solarized Light',
    'sunburst': 'Sunburst',
    'tomorrow': 'Tomorrow',
    'tomorrow-night': 'Tomorrow Night',
    'tomorrow-night-blue': 'Tomorrow Night Blue',
    'tomorrow-night-bright': 'Tomorrow Night Bright',
    'tomorrow-night-eighties': 'Tomorrow Night Eighties',
    'vs': 'Vs',
    'vs2015': 'Vs 2015',
    'xcode': 'Xcode',
    'xt256': 'Xt 256',
    'zenburn': 'Zenburn',
}
