export default {
    bright: {
        'ace/theme/chrome': 'Chrome',
        'ace/theme/clouds': 'Clouds',
        'ace/theme/crimson_editor': 'Crimson Editor',
        'ace/theme/dawn': 'Dawn',
        'ace/theme/dreamweaver': 'Dreamweaver',
        'ace/theme/eclipse': 'Eclipse',
        'ace/theme/github': 'GitHub',
        'ace/theme/iplastic': 'IPlastic',
        'ace/theme/katzenmilch': 'KatzenMilch',
        'ace/theme/kuroir': 'Kuroir',
        'ace/theme/solarized_light': 'Solarized Light',
        'ace/theme/sqlserver': 'SQL Server',
        'ace/theme/textmate': 'TextMate',
        'ace/theme/tomorrow': 'Tomorrow',
        'ace/theme/xcode': 'XCode',
    },
    dark: {
        'ace/theme/ambiance': 'Ambiance',
        'ace/theme/chaos': 'Chaos',
        'ace/theme/clouds_midnight': 'Clouds Midnight',
        'ace/theme/cobalt': 'Cobalt',
        'ace/theme/dracula': 'Dracula',
        'ace/theme/gob': 'Green on Black',
        'ace/theme/gruvbox': 'Gruvbox',
        'ace/theme/idle_fingers': 'idle Fingers',
        'ace/theme/kr_theme': 'krTheme',
        'ace/theme/merbivore': 'Merbivore',
        'ace/theme/merbivore_soft': 'Merbivore Soft',
        'ace/theme/mono_industrial': 'Mono Industrial',
        'ace/theme/monokai': 'Monokai',
        'ace/theme/pastel_on_dark': 'Pastel on dark',
        'ace/theme/solarized_dark': 'Solarized Dark',
        'ace/theme/terminal': 'Terminal',
        'ace/theme/tomorrow_night': 'Tomorrow Night',
        'ace/theme/tomorrow_night_blue': 'Tomorrow Night Blue',
        'ace/theme/tomorrow_night_bright': 'Tomorrow Night Bright',
        'ace/theme/tomorrow_night_eighties': 'Tomorrow Night 80s',
        'ace/theme/twilight': 'Twilight',
        'ace/theme/vibrant_ink': 'Vibrant Ink',
    },
}
